# Site
name: "marandaneto"
title: "marandaneto's blog."
description: "My personal blog to share my own ideas of software development."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  marandaneto:
    name: Manoel Aranda Neto
    display_name: Manoel
    gravatar: 2c153c3d25780832605cff7803a17e3a
    email: marandaneto@gmail.com
    web: https://marandaneto.github.io
    twitter: https://twitter.com/marandaneto
    description: "Android Engineer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
